#!/usr/bin/env node
// Generates the favicon set in public/ from one inline definition: the
// Lucide `sailboat` glyph (lucide.dev, ISC license) on the app's accent-blue
// tile (#156cdd = sRGB of --selected oklch(0.55 0.19 258) in
// src/styles/app.css). Two variants: a rounded tile for browser favicons
// (svg/png/ico) and a full-bleed square for apple-touch-icon + maskable
// android icons, where the platform applies its own corner mask.
//
// Run via `pnpm favicons:generate`.

import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import pngToIco from 'png-to-ico'
import sharp from 'sharp'

const publicDir = resolve(dirname(fileURLToPath(import.meta.url)), '../public')

const TILE_BLUE = '#156cdd'

// Lucide `sailboat` path data (24x24 viewBox).
const MAST = 'M10 2v15'
const HULL = 'M7 22a4 4 0 0 1-4-4 1 1 0 0 1 1-1h16a1 1 0 0 1 1 1 4 4 0 0 1-4 4z'
const SAIL = 'M9.159 2.46a1 1 0 0 1 1.521-.193l9.977 8.98A1 1 0 0 1 20 13H4a1 1 0 0 1-.824-1.567z'

// Hull and sail are filled, not stroke-only as Lucide draws them — solid
// shapes stay legible at 16px where thin strokes smear. Their 0.5 stroke
// only softens the corners; Lucide's own stroke-width 2 blobs the sail
// into an eject symbol once filled. The mast is a bare line, so it keeps
// the full stroke-width 2 to survive small sizes.
function tileSvg({ cornerRadius, glyphScale }) {
  const offset = (64 - 24 * glyphScale) / 2
  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <!-- Sailboat glyph from Lucide (lucide.dev), ISC license. Generated by scripts/generateFavicons.mjs -->
  <rect width="64" height="64" rx="${cornerRadius}" fill="${TILE_BLUE}"/>
  <g transform="translate(${offset} ${offset}) scale(${glyphScale})" stroke="#fff" stroke-linecap="round" stroke-linejoin="round">
    <path d="${MAST}" fill="none" stroke-width="2"/>
    <path d="${HULL}" fill="#fff" stroke-width="0.5"/>
    <path d="${SAIL}" fill="#fff" stroke-width="0.5"/>
  </g>
</svg>
`
}

const rounded = tileSvg({ cornerRadius: 14, glyphScale: 1.6 })
// Glyph at 56% keeps it inside the maskable icon's 80% safe zone.
const fullBleed = tileSvg({ cornerRadius: 0, glyphScale: 1.5 })

function renderPng(svg, size) {
  return sharp(Buffer.from(svg), { density: (72 * size) / 64 })
    .resize(size, size)
    .png()
    .toBuffer()
}

const png16 = await renderPng(rounded, 16)
const png32 = await renderPng(rounded, 32)

const outputs = [
  ['favicon.svg', rounded],
  ['favicon-16x16.png', png16],
  ['favicon-32x32.png', png32],
  ['favicon.ico', await pngToIco([png16, png32])],
  ['apple-touch-icon.png', await renderPng(fullBleed, 180)],
  ['android-chrome-192x192.png', await renderPng(fullBleed, 192)],
  ['android-chrome-512x512.png', await renderPng(fullBleed, 512)],
]

for (const [name, data] of outputs) {
  writeFileSync(resolve(publicDir, name), data)
  console.log(`[generateFavicons] wrote public/${name}`)
}
